### ISSUE TITLE
Rogue "Detect traps" should be hidden from buff pane

### ISSUE THREAD

**Issue by antisocial89** [antisocial89/realtbc_issues#24]
The "Detect traps" passive is in the buff character pane and should be invisible.

**Comment by nairyo** [comment]
I believe this was the case in TBC ?

**Comment by Saben65** [comment]
Do you have a source for this? I don't think passives were hidden until later. Posts about people complaining about passives not showing up in the spellbook are only 2 years old.

http://us.battle.net/wow/en/forum/topic/15141444305
http://www.mmo-champion.com/threads/1630641-Any-way-to-still-see-ALL-of-our-passives-that-Blizz-has-hidden-from-spell-book
http://www.gamefaqs.com/boards/534914-world-of-warcraft/70536207

**Comment by nairyo** [comment]
fixed in next push
